# fly.toml app configuration file generated for 3kfa02jd9kf0k2dd2 on 2025-04-18T21:43:33Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '3kfa02jd9kf0k2dd2'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
